// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgoogleanalyticstests.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxGoogleAnalyticsTests module

	public static java.lang.String getGA_PROJECT_TOKEN()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxGoogleAnalyticsTests.GA_PROJECT_TOKEN");
	}
}