// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxnlp.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxnlp.impl.MxNlpConnector;

public class InitNetwork extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String NetworkName;
	private java.lang.String NetworkResourceLocation;
	private java.lang.String TrainingSetResourceLocation;

	public InitNetwork(IContext context, java.lang.String NetworkName, java.lang.String NetworkResourceLocation, java.lang.String TrainingSetResourceLocation)
	{
		super(context);
		this.NetworkName = NetworkName;
		this.NetworkResourceLocation = NetworkResourceLocation;
		this.TrainingSetResourceLocation = TrainingSetResourceLocation;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        //throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
        MxNlpConnector connector = new MxNlpConnector();
        connector.setLogger(logger);
//        connector.initNetwork(NetworkName, NetworkResourceLocation, TrainingSetResourceLocation);

        connector.initNetwork("test1",
                "mxnlptest/test1_network.zip",
                "/mxnlptest/test1_sentences.txt");
        String label = connector.predict("test1", "help me");
        logger.info("label: " + label);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "InitNetwork";
	}

	// BEGIN EXTRA CODE
    private ILogNode logger = Core.getLogger(MxNlpConnector.LOGNODE);
	// END EXTRA CODE
}
