// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxnlp.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class Predict extends CustomJavaAction<java.lang.String>
{
	private java.lang.String NetworkName;
	private java.lang.String Sentence;

	public Predict(IContext context, java.lang.String NetworkName, java.lang.String Sentence)
	{
		super(context);
		this.NetworkName = NetworkName;
		this.Sentence = Sentence;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "Predict";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
