// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutils.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxutils.proxies.constants.Constants;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

public class SetConfigFromProperty extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String PropertyFileName;

	public SetConfigFromProperty(IContext context, java.lang.String PropertyFileName)
	{
		super(context);
		this.PropertyFileName = PropertyFileName;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        try (
                FileInputStream fis = new FileInputStream(PropertyFileName)
        ) {
            Properties props = new Properties();
            props.load(fis);

            Map<String, Object> newConfig = new HashMap<String, Object>();
            props.forEach((k, v) -> {
                newConfig.put(k.toString(), v);
                logger.info(String.format("Set config from property: %s = %s, %s, %s", k, v, k, PropertyFileName));
            });
            logger.info(String.format("Confguration map: %s", newConfig));
            Core.getConfiguration().updateConfiguration(newConfig, true);
            Core.getConfiguration().checkConfig();

			logger.info(String.format("Access key id %s", Constants.getAWS_ACCESS_KEY_ID()));
        } catch (FileNotFoundException e) {
            logger.info(String.format("Properties file %s not found", PropertyFileName));
        }
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SetConfigFromProperty";
	}

	// BEGIN EXTRA CODE
    private ILogNode logger = Core.getLogger("SetConfigFromProperty");
	// END EXTRA CODE
}
