// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxutils.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Convert unix epoch timestamp to DateTime
 */
public class UnixEpochToDateTime extends CustomJavaAction<java.util.Date>
{
	private Long UnixEpoch;

	public UnixEpochToDateTime(IContext context, Long UnixEpoch)
	{
		super(context);
		this.UnixEpoch = UnixEpoch;
	}

	@Override
	public java.util.Date executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public String toString()
	{
		return "UnixEpochToDateTime";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
