// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxutils.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxUtils module

	public static java.lang.String getAWS_ACCESS_KEY_ID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxUtils.AWS_ACCESS_KEY_ID");
	}

	public static java.lang.String getAWS_REGION()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxUtils.AWS_REGION");
	}

	public static java.lang.String getAWS_SECRET_ACCESS_KEY()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxUtils.AWS_SECRET_ACCESS_KEY");
	}

	public static java.lang.String getMX_UTILS_CONFIG_PATH()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("MxUtils.MX_UTILS_CONFIG_PATH");
	}
}