// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawss3.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import mxawss3.impl.AwsS3Connector;
import org.apache.commons.io.IOUtils;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;

public class S3CopyFileDocumentToBucket extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String Region;
	private java.lang.String Bucket;
	private IMendixObject __FileDocumentParameter1;
	private system.proxies.FileDocument FileDocumentParameter1;

	public S3CopyFileDocumentToBucket(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String Region, java.lang.String Bucket, IMendixObject FileDocumentParameter1)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.Region = Region;
		this.Bucket = Bucket;
		this.__FileDocumentParameter1 = FileDocumentParameter1;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.FileDocumentParameter1 = __FileDocumentParameter1 == null ? null : system.proxies.FileDocument.initialize(getContext(), __FileDocumentParameter1);

		// BEGIN USER CODE
		String s3FilePath=null;
        try {
            connector.setLogger(logger);
            connector.setAwsCredentials(this.AwsAccessKeyId, this.AwsSecretAccessKey);

            String tmpfileName = Core.getConfiguration().getTempPath() + System.getProperty("file.separator") +
                    this.FileDocumentParameter1.getFileID().toString();
            logger.info("Tmp file: " + tmpfileName);

            InputStream is = Core.getFileDocumentContent(this.getContext(), FileDocumentParameter1.getMendixObject());
            OutputStream os = new FileOutputStream(tmpfileName);
            IOUtils.copy(is, os);
            File file = new File(tmpfileName);

            logger.info("Tmp file size: " + file.length());
            logger.info("Has contents: " + FileDocumentParameter1.getHasContents());
			connector.setRegion(this.Region);
			s3FilePath = connector.copyFileDocumentToS3(this.Bucket, this.FileDocumentParameter1.getFileID().toString(), file);

        } catch (Exception e) {
            logger.warn(e.getMessage());
            return null;
        }
        return s3FilePath;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "S3CopyFileDocumentToBucket";
	}

	// BEGIN EXTRA CODE
    private final ILogNode logger = Core.getLogger(AwsS3Connector.LOG_NODE);
    private final AwsS3Connector connector = new AwsS3Connector();
	// END EXTRA CODE
}
