// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxgoogleanalytics.actions;

import mxgoogleanalytics.proxies.constants.Constants;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxgoogleanalytics.impl.GoogleAnalyticsConnector;

public class GaTrackEvent extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ProjectToken;
	private java.lang.String ClientId;
	private java.lang.String UserId;
	private java.lang.String EventCategory;
	private java.lang.String EventAction;
	private java.lang.String EventLabel;
	private java.lang.Long EventValue;

	public GaTrackEvent(IContext context, java.lang.String ProjectToken, java.lang.String ClientId, java.lang.String UserId, java.lang.String EventCategory, java.lang.String EventAction, java.lang.String EventLabel, java.lang.Long EventValue)
	{
		super(context);
		this.ProjectToken = ProjectToken;
		this.ClientId = ClientId;
		this.UserId = UserId;
		this.EventCategory = EventCategory;
		this.EventAction = EventAction;
		this.EventLabel = EventLabel;
		this.EventValue = EventValue;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        GoogleAnalyticsConnector conn = new GoogleAnalyticsConnector();
        conn.setLogger(Core.getLogger(GoogleAnalyticsConnector.LOGNODE));
        conn.setDebug(Constants.getGA_DEBUG());
        conn.trackEvent(this.ProjectToken, this.ClientId, this.UserId, this.EventCategory, this.EventAction, this.EventLabel, this.EventValue);
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GaTrackEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
