// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxutils.proxies;

public class MultiSeriesDataset
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject multiSeriesDatasetMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MxUtils.MultiSeriesDataset";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Color("Color"),
		Label("Label"),
		SortingValue("SortingValue"),
		MultiSeriesDataset_DataPoint("MxUtils.MultiSeriesDataset_DataPoint");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MultiSeriesDataset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MxUtils.MultiSeriesDataset"));
	}

	protected MultiSeriesDataset(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject multiSeriesDatasetMendixObject)
	{
		if (multiSeriesDatasetMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MxUtils.MultiSeriesDataset", multiSeriesDatasetMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MxUtils.MultiSeriesDataset");

		this.multiSeriesDatasetMendixObject = multiSeriesDatasetMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MultiSeriesDataset.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static mxutils.proxies.MultiSeriesDataset initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mxutils.proxies.MultiSeriesDataset.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static mxutils.proxies.MultiSeriesDataset initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mxutils.proxies.MultiSeriesDataset(context, mendixObject);
	}

	public static mxutils.proxies.MultiSeriesDataset load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mxutils.proxies.MultiSeriesDataset.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Color
	 */
	public final String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final String getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of Label
	 */
	public final String getLabel()
	{
		return getLabel(getContext());
	}

	/**
	 * @param context
	 * @return value of Label
	 */
	public final String getLabel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Label.toString());
	}

	/**
	 * Set value of Label
	 * @param label
	 */
	public final void setLabel(String label)
	{
		setLabel(getContext(), label);
	}

	/**
	 * Set value of Label
	 * @param context
	 * @param label
	 */
	public final void setLabel(com.mendix.systemwideinterfaces.core.IContext context, String label)
	{
		getMendixObject().setValue(context, MemberNames.Label.toString(), label);
	}

	/**
	 * @return value of SortingValue
	 */
	public final Integer getSortingValue()
	{
		return getSortingValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortingValue
	 */
	public final Integer getSortingValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.SortingValue.toString());
	}

	/**
	 * Set value of SortingValue
	 * @param sortingvalue
	 */
	public final void setSortingValue(Integer sortingvalue)
	{
		setSortingValue(getContext(), sortingvalue);
	}

	/**
	 * Set value of SortingValue
	 * @param context
	 * @param sortingvalue
	 */
	public final void setSortingValue(com.mendix.systemwideinterfaces.core.IContext context, Integer sortingvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortingValue.toString(), sortingvalue);
	}

	/**
	 * @return value of MultiSeriesDataset_DataPoint
	 */
	public final java.util.List<mxutils.proxies.DataPoint> getMultiSeriesDataset_DataPoint() throws com.mendix.core.CoreException
	{
		return getMultiSeriesDataset_DataPoint(getContext());
	}

	/**
	 * @param context
	 * @return value of MultiSeriesDataset_DataPoint
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<mxutils.proxies.DataPoint> getMultiSeriesDataset_DataPoint(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<mxutils.proxies.DataPoint> result = new java.util.ArrayList<mxutils.proxies.DataPoint>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MultiSeriesDataset_DataPoint.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(mxutils.proxies.DataPoint.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of MultiSeriesDataset_DataPoint
	 * @param multiseriesdataset_datapoint
	 */
	public final void setMultiSeriesDataset_DataPoint(java.util.List<mxutils.proxies.DataPoint> multiseriesdataset_datapoint)
	{
		setMultiSeriesDataset_DataPoint(getContext(), multiseriesdataset_datapoint);
	}

	/**
	 * Set value of MultiSeriesDataset_DataPoint
	 * @param context
	 * @param multiseriesdataset_datapoint
	 */
	public final void setMultiSeriesDataset_DataPoint(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<mxutils.proxies.DataPoint> multiseriesdataset_datapoint)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (mxutils.proxies.DataPoint proxyObject : multiseriesdataset_datapoint)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.MultiSeriesDataset_DataPoint.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return multiSeriesDatasetMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mxutils.proxies.MultiSeriesDataset that = (mxutils.proxies.MultiSeriesDataset) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MxUtils.MultiSeriesDataset";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
