// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mixpanel.actions;

import com.mendix.core.Core;
import com.mixpanel.mixpanelapi.ClientDelivery;
import com.mixpanel.mixpanelapi.MessageBuilder;
import com.mixpanel.mixpanelapi.MixpanelAPI;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mixpanel.impl.MixPanelConnector;
import org.json.JSONObject;

public class SendEvent extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String ProjectToken;
	private java.lang.String DistinctId;
	private java.lang.String EventName;
	private java.lang.String EventProperties;

	public SendEvent(IContext context, java.lang.String ProjectToken, java.lang.String DistinctId, java.lang.String EventName, java.lang.String EventProperties)
	{
		super(context);
		this.ProjectToken = ProjectToken;
		this.DistinctId = DistinctId;
		this.EventName = EventName;
		this.EventProperties = EventProperties;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		MixPanelConnector conn = new MixPanelConnector();
		conn.setLogger(Core.getLogger(MixPanelConnector.LOGNODE));
		conn.sendEvent(this.ProjectToken, this.DistinctId, this.EventName, this.EventProperties);
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "SendEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
