// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxawsrekognition.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import mxawsrekognition.AwsRekognitionConnector;

public class DetectFaces extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AwsAccessKeyId;
	private java.lang.String AwsSecretAccessKey;
	private java.lang.String AwsRegion;
	private java.lang.String Bucket;
	private java.lang.String Key;

	public DetectFaces(IContext context, java.lang.String AwsAccessKeyId, java.lang.String AwsSecretAccessKey, java.lang.String AwsRegion, java.lang.String Bucket, java.lang.String Key)
	{
		super(context);
		this.AwsAccessKeyId = AwsAccessKeyId;
		this.AwsSecretAccessKey = AwsSecretAccessKey;
		this.AwsRegion = AwsRegion;
		this.Bucket = Bucket;
		this.Key = Key;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
        logger.info(String.format("executeAction - bucket: %s, key: %s, region: %s", this.Bucket, this.Key, this.AwsRegion));

        AwsRekognitionConnector conn = new AwsRekognitionConnector();
        conn.setLogger(logger);
        String jsonResult = conn.detectFaces(AwsAccessKeyId, AwsSecretAccessKey, this.Key, this.Bucket, this.AwsRegion);
        logger.info("DetectFaces result: " + jsonResult);
        return jsonResult;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DetectFaces";
	}

	// BEGIN EXTRA CODE
    private final ILogNode logger = Core.getLogger("AwsRekognition");
	// END EXTRA CODE
}
