// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxgoogleanalytics.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the MxGoogleAnalytics module

	public static boolean getGA_DEBUG()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("MxGoogleAnalytics.GA_DEBUG");
	}
}